/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentCopy: typeof import('./src/components/ContentCopy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    QRCodeScanner: typeof import('./src/components/QRCodeScanner.vue')['default']
    ScoutingForm: typeof import('./src/components/ScoutingForm.vue')['default']
  }
}
